### ISSUE TITLE
加入require.context后怎么调试

### ISSUE THREAD

**Issue by infeng** [wssgcg1213/koa2-react-server-side-render-boilerplate#104]
我在客户端代码引用require.context后，因为require.context是webpack的东西，所以`npm start`就会报以下错误`require.context is not a function`，想问一下怎么解决这个好？

**Comment by wssgcg1213** [comment]
sorry，没有支持 require.context 的计划...  是什么需求必须要使用这个API？

**Comment by infeng** [comment]
项目用到require.context批量引用reducer和saga

**Comment by infeng** [comment]
引入[webpack-isomorphic-tools](https://github.com/halt-hammerzeit/webpack-isomorphic-tools)解决require.context的问题怎样

**Comment by wssgcg1213** [comment]
欢迎尝试，如果有好的经验可以分享一下
