### ISSUE TITLE
chokidar去监听app、platforms下代码变动没有实现替换

### ISSUE THREAD

**Issue by y190** [wssgcg1213/koa2-react-server-side-render-boilerplate#110]
有提示Clearing module cache，但是访问后仍然返回之前的内容，请问一下，是不是还少了什么步骤。

**Comment by wssgcg1213** [comment]
你是修改了哪部分的文件？有没有详细的可复现的操作过程

**Comment by xincyang** [comment]
我把koa-webapck-middleware换成了koa-webpack-dev-middleware和koa-webpack-hot-middleware，这个会有什么影响么？
