### ISSUE TITLE
我怎么加入mongodb.

### ISSUE THREAD

**Issue by chengnuo** [wssgcg1213/koa2-react-server-side-render-boilerplate#113]
我看你的源代码，有对mongodb的基本配置。我是沿用你的，还是我自己搞一个新的。

**Comment by wssgcg1213** [comment]
model 层的实现并没有限制，我也没有添加 mongodb 的实例文件呀？  
platforms/server 下的实现完全是一个可控的 MVC 架构的 koa app，直接使用 mongodb 官网推荐的方式维护 model 层就可以了

**Comment by chengnuo** [comment]
哦，好的，那我自己搞一个。

**Comment by chengnuo** [comment]
Sequelize 和 mongoose 是什么区别。

**Comment by chengnuo** [comment]
Sequelize好像搞mysql 那些关系型的比较多，我自己搞个mongoose算了。
