### ISSUE TITLE
fetch post 后端如何获取post的数据

### ISSUE THREAD

**Issue by lcsoftware** [wssgcg1213/koa2-react-server-side-render-boilerplate#137]
我在前端调用fetch方法，并以post方式提交数据：
fetch(URL, {
			method: 'POST', 
			body: param, 
			headers: { 'Accept': 'application/json', 'Content-Type': 'application/json'}
		}

在api端，如何获取这个请求的body参数数据，并影响前端？

这是我在api端的controller代码，但都不能获取body数据，也不能影响到前端
export default (ctx, next) => {
	console.log('*******************')
	console.log(ctx.request);
	console.log(this);
	console.log('*******************************************************************************')
	console.log(ctx.body) 
}

**Comment by wssgcg1213** [comment]
```ctx.request.body```

参考这个https://github.com/koajs/bodyparser
