### ISSUE TITLE
npm start 时出现错误 http 404 错

### ISSUE THREAD

**Issue by chenshuxian** [wssgcg1213/koa2-react-server-side-render-boilerplate#166]
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/koa2-react-isomorphic-boilerplate
npm ERR! 404 
npm ERR! 404  'koa2-react-isomorphic-boilerplate' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
请问这问题要如何解决

**Comment by wssgcg1213** [comment]
你是怎么启动的

**Comment by chenshuxian** [comment]
npm start

**Comment by wssgcg1213** [comment]
node 是哪个版本的  我试一下

**Comment by chenshuxian** [comment]
node v7.8.0
 npm  v4.2.0

**Comment by chenshuxian** [comment]
请问有办法解决吗

**Comment by wssgcg1213** [comment]
你是不是把这个当成模块使用了，它不是一个模块

**Comment by wssgcg1213** [comment]
我试了一下 node7是可以的
![image](https://cloud.githubusercontent.com/assets/3922719/25466440/4a53ec6c-2b3b-11e7-96b2-c6a517aa4d81.png)
